export const defaultMetadata = {
  page_settings: {
    currentPageSize: 'A4',
    height: 1122.519685,
    width: 793.7007874,
    marginTop: 0,
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    headerHeight: 0,
    footerHeight: 200,
    headerHeightWithMargin: 0,
    footerHeightWithMargin: 0,
    UOM: 'px',
    pdfPrintDPI: 96,
    fonts: {
      Inter: {
        weight: ['400'],
        italic: [],
      },
      Roboto: {
        weight: ['400', '700'],
        italic: [],
      },
    },
  },
};

export const defaultSource = {
  elements: [
    {
      id: '4b0ca436-a997-46b2-b4db-ad9d464715c8',
      content: [],
      name: 'Section',
      originalElement: 'div',
      styles: {
        display: 'flex',
        'flex-direction': 'column',
        width: '100%',
        height: '100%',
        'font-family': 'Inter',
        'padding-left': '41px',
        'padding-top': '41px',
        'padding-bottom': '41px',
        'padding-right': '41px',
      },
      attributes: {
        'data-page-break': '1',
        'data-page-header': '1',
        'data-page-footer': '1',
        'data-page-watermark': '1',
      },
      type: '__body',
    },
  ],
  headers: {
    id: '80d71544-5d83-4a37-99aa-9a9b308d2016',
    content: [],
    name: 'Headers',
    originalElement: 'div',
    styles: {
      display: 'flex',
      'flex-direction': 'column',
      width: '100%',
      height: '100%',
      'font-family': 'Inter',
      'padding-right': '20px',
      'padding-top': '10px',
      'padding-bottom': '10px',
      'padding-left': '20px',
      'justify-content': 'center',
      'align-items': 'center',
    },
    attributes: {},
    type: '__body',
    showToAllSection: true,
    sectionIndex: [],
  },
  footers: {
    id: '95b63941-de0e-4b5f-b1cb-f3b4d6d7b861',
    content: [],
    name: 'Footers',
    originalElement: 'div',
    styles: {
      display: 'flex',
      'flex-direction': 'row',
      width: '100%',
      height: '100%',
      'font-family': 'Inter',
      'justify-content': 'space-between',
      'align-items': 'flex-start',
      'padding-left': '0px',
      'padding-right': '0px',
      'padding-top': '10px',
      'padding-bottom': '0px',
    },
    attributes: {},
    type: '__body',
    showToAllSection: true,
    sectionIndex: [],
  },
  watermark: {
    id: 'a7084b35-0a01-4df6-88bb-643b9ddaf5ce',
    name: 'Watermark',
    content: [],
    originalElement: 'div',
    styles: {
      display: 'flex',
      'flex-direction': 'column',
      width: '100%',
      height: '100%',
      'font-family': 'Inter',
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
      'justify-content': 'center',
      'align-items': 'center',
      opacity: 0.15,
    },
    attributes: {},
    isRepeaterElement: false,
    type: '__body',
    usingWatermark: true,
    previewWatermark: true,
    showToAllSection: true,
    sectionIndex: [],
  },
};
